parameters:
  wordpress.driver.wpcli.class: PaulGibbs\WordpressBehatExtension\Driver\WpcliDriver
  wordpress.element.wpcli.content.class: PaulGibbs\WordpressBehatExtension\Driver\Element\Wpcli\ContentElement

services:
  wordpress.driver.wpcli:
    class: %wordpress.driver.wpcli.class%
    arguments:
      - %wordpress.driver.wpcli.alias%
      - %wordpress.path%
      - %mink.base_url%
      - %wordpress.driver.wpcli.binary%
    tags:
      - { name: wordpress.driver, alias: wpcli }

  wordpress.element.wpcli.content:
    class: %wordpress.element.wpcli.content.class%
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: wpcli }
